//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align: center&quot;&gt;
        ///                                    &lt;span style=&quot;color: #a46c2a; font-weight: bold&quot;&gt;Address:&lt;/span&gt; 8th Floor, No 77 Nguyen Thai Hoc street, Dien Bien quarter, Ba Dinh district, Ha Noi city, Viet Nam
        ///                        &lt;br /&gt;
        ///                                    &lt;span style=&quot;color: #a46c2a; font-weight: bold;&quot;&gt;Phone:&lt;/span&gt; 84-243 926 4009 &amp;nbsp;&amp;nbsp;         
        ///                        &lt;span style=&quot;color: #a46c2a; font-weight: bold;&quot;&gt;Email:&lt;/span&gt; sales@orientalsails.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Feedback_Address_Phone_Email {
            get {
                return ResourceManager.GetString("Feedback_Address_Phone_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose start date.
        /// </summary>
        internal static string Feedback_ChooseStartDate {
            get {
                return ResourceManager.GetString("Feedback_ChooseStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise.
        /// </summary>
        internal static string Feedback_Cruise {
            get {
                return ResourceManager.GetString("Feedback_Cruise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER FEEDBACK.
        /// </summary>
        internal static string Feedback_CUSTOMERFEEDBACK {
            get {
                return ResourceManager.GetString("Feedback_CUSTOMERFEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there any thing you would like to tell us.
        /// </summary>
        internal static string Feedback_IsThereAnyThingYouWouldLikeToTellUs {
            get {
                return ResourceManager.GetString("Feedback_IsThereAnyThingYouWouldLikeToTellUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Feedback_PhoneNumber {
            get {
                return ResourceManager.GetString("Feedback_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number are only numbers.
        /// </summary>
        internal static string Feedback_PhoneNumberAreOnlyNumbers {
            get {
                return ResourceManager.GetString("Feedback_PhoneNumberAreOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number exceed 11 characters.
        /// </summary>
        internal static string Feedback_PhoneNumberExceed11Characters {
            get {
                return ResourceManager.GetString("Feedback_PhoneNumberExceed11Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check start date format again.
        /// </summary>
        internal static string Feedback_PleaseCheckStartDateFormatAgain {
            get {
                return ResourceManager.GetString("Feedback_PleaseCheckStartDateFormatAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose cruise.
        /// </summary>
        internal static string Feedback_PleaseChooseCruise {
            get {
                return ResourceManager.GetString("Feedback_PleaseChooseCruise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose cruise first.
        /// </summary>
        internal static string Feedback_PleaseChooseCruiseFirst {
            get {
                return ResourceManager.GetString("Feedback_PleaseChooseCruiseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose room.
        /// </summary>
        internal static string Feedback_PleaseChooseRoom {
            get {
                return ResourceManager.GetString("Feedback_PleaseChooseRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose start date.
        /// </summary>
        internal static string Feedback_PleaseChooseStartDate {
            get {
                return ResourceManager.GetString("Feedback_PleaseChooseStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out this field.
        /// </summary>
        internal static string Feedback_PleaseFillOutThisField {
            get {
                return ResourceManager.GetString("Feedback_PleaseFillOutThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your phone number.
        /// </summary>
        internal static string Feedback_PleaseInputYourPhoneNumber {
            get {
                return ResourceManager.GetString("Feedback_PleaseInputYourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Feedback_Room {
            get {
                return ResourceManager.GetString("Feedback_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Feedback_Select {
            get {
                return ResourceManager.GetString("Feedback_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Feedback_Send {
            get {
                return ResourceManager.GetString("Feedback_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string Feedback_StartDate {
            get {
                return ResourceManager.GetString("Feedback_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-size: 14px; clear: both&quot;&gt;
        ///                                    &lt;span style=&quot;font-weight: bold&quot;&gt;Dear Valued Customer, &lt;/span&gt;
        ///                                    &lt;br /&gt;
        ///                                    Thank you for choosing &lt;span style=&quot;font-weight: bold&quot;&gt;ORIENTAL SAILS&lt;/span&gt;. It is our great pleasure to provide you the best quality of service always.
        ///                                    &lt;br /&gt;
        ///                                    Your assistance in completing this form is greatly appre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Feedback_ThankYou {
            get {
                return ResourceManager.GetString("Feedback_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your feedback.
        /// </summary>
        internal static string Feedback_ThankYouForYourFeedback {
            get {
                return ResourceManager.GetString("Feedback_ThankYouForYourFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string Feedback_YourName {
            get {
                return ResourceManager.GetString("Feedback_YourName", resourceCulture);
            }
        }
    }
}
